version: '3'

services:
  web:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    platform: linux/amd64
    command: python3 app/app.py
    volumes:
      - './app:/amenom/app'
    ports:
      - "3000:3000"
